server:
  port:8080
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
